name: ddd_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.2.1
  shelf_swagger_ui: ^1.0.0+2
  eda: ^0.1.0

dev_dependencies:
  http: ^1.2.1
  lints: ^4.0.0
  test: ^1.25.7
